---
name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  embedded_build:
    name: Embedded Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gcc: ["8-2019-q3", "9-2020-q2", "10.3-2021.10"]
        configuration: ["RelWithDebInfo"]
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - name: Install GNU Arm Embedded Toolchain ${{ matrix.gcc }}
        uses: carlosperate/arm-none-eabi-gcc-action@2ff22aeffd30b95d7238914a6a83e57069a18d40
        with:
          release: ${{ matrix.gcc }}
      - uses: seanmiddleditch/gha-setup-ninja@16b940825621068d98711680b6c3ff92201f8fc0
      - uses: hendrikmuhs/ccache-action@657bab9aeb32eb6d913c2e6882efad4bb7536d94
        with:
          key: ${{ matrix.gcc }}-${{ matrix.configuration }}
      - run: |
          sudo apt-get update && sudo apt-get install --no-install-recommends -y xsltproc
          echo "::add-matcher::.github/matchers/gcc-problem-matcher.json"
          cmake --preset host -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build --preset host-${{ matrix.configuration }}
          cmake --preset stm32f767 -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build --preset stm32f767-${{ matrix.configuration }}
