---
name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  embedded_build:
    name: Embedded Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gcc: ["8-2019-q3", "9-2020-q2", "10.3-2021.10"]
        configuration: ["RelWithDebInfo"]
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Install GNU Arm Embedded Toolchain ${{ matrix.gcc }}
        uses: carlosperate/arm-none-eabi-gcc-action@828dd7ce6ea122338b9bafd5d9969de1b5dfbfe2
        with:
          release: ${{ matrix.gcc }}
      - uses: seanmiddleditch/gha-setup-ninja@16b940825621068d98711680b6c3ff92201f8fc0
      - uses: hendrikmuhs/ccache-action@621a41397ed83711c72862638d9ff6e63fca3041
        with:
          key: ${{ matrix.gcc }}-${{ matrix.configuration }}
      - run: |
          sudo apt-get update && sudo apt-get install --no-install-recommends -y xsltproc
          echo "::add-matcher::.github/matchers/gcc-problem-matcher.json"
          cmake --preset host -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build --preset host-${{ matrix.configuration }}
          cmake --preset stm32f767 -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build --preset stm32f767-${{ matrix.configuration }}
