---
name: Security

on:
  branch_protection_rule:
  schedule:
    - cron: "33 8 * * 6"
  push:
    branches: [main]

permissions: read-all

jobs:
  analysis:
    name: OSSF Scorecards
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          persist-credentials: false
      - name: Analysis
        uses: ossf/scorecard-action@ce330fde6b1a5c9c75b417e7efc510b822a35564
        with:
          results_file: scorecards.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_READ_TOKEN }}
          publish_results: true
      - uses: github/codeql-action/upload-sarif@2ca79b6fa8d3ec278944088b4aa5f46912db5d63
        with:
          sarif_file: scorecards.sarif
