---
name: Security

on:
  branch_protection_rule:
  schedule:
    - cron: "33 8 * * 6"
  push:
    branches: [main]

permissions: read-all

jobs:
  analysis:
    name: OSSF Scorecards
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false
      - name: Analysis
        uses: ossf/scorecard-action@e363bfca00e752f91de7b7d2a77340e2e523cb18
        with:
          results_file: scorecards.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_READ_TOKEN }}
          publish_results: true
      - uses: github/codeql-action/upload-sarif@86f3159a697a097a813ad9bfa0002412d97690a4
        with:
          sarif_file: scorecards.sarif
